name: Github Action Test
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          run: echo "Deployed"
      - name: Install node_modules
        run: yarn
      - name: Lint
        run: yarn lint
