name: Github Action Test
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build the project
        run: yarn build
      - name: Deploy
        run: firebase deploy
        run: echo "Deployed" 
